### ISSUE TITLE
Provide OSGi Meta-information

### ISSUE THREAD

**Issue by laeubi** [openjson/openjson#11]
To make it easier to use this lib in OSGi-Env it would be cool to add OSGi-Metainfos to the Manifest. This can be done manually or automatic e.g. with http://njbartlett.name/2015/03/27/announcing-bnd-maven-plugin.html

Since this meta-infos are only added to the manifest and no other dependecies are introduced this can be done without influence other usages.

This relates to https://issues.apache.org/jira/browse/WICKET-6402 / https://ops4j1.jira.com/browse/PAXWICKET-486

**Comment by solomax** [comment]
Maybe you can provide PR?

**Comment by laeubi** [comment]
Can you tell if this is already released (what version?)

**Comment by solomax** [comment]
Latest version is 1.0.10, it was released in October, so it should have these changes ....
