### ISSUE TITLE
release tags corresponding to the Maven Central releases?

### ISSUE THREAD

**Issue by tmancill** [openjson/openjson#14]
Hi,

As best as I can tell, these are the sources used to create https://search.maven.org/artifact/com.github.openjson/openjson/1.0.10/jar.  However, the tags in this repo are those that came along with the fork of [tdunning/open-json](https://github.com/tdunning/open-json) and use a different numbering scheme.  Could someone with permissions create a tag and a release that corresponds to https://github.com/openjson/openjson/blob/master/pom.xml#L9?  (And perhaps even delete the tdunning/open-json tags?)

This might save a bit of confusion for developers trying to find the sources in Github, and it will make it easier to package this library for Debian.

Thank you,
tony

**Comment by solomax** [comment]
@mfursov could you please add missing tags?

**Comment by martin-g** [comment]
Done!

**Comment by tmancill** [comment]
Thank you!
