### ISSUE TITLE
Change Method visibility

### ISSUE THREAD

**Issue by solomax** [openjson/openjson#5]
Hello All,

I would like to change visibility of JSONStringer::beforeKey method
I tried to create my own Stringer and override key(String) method, but currently this seems to be impossible

The change is trivial, I created this issue to discuss: maybe visibility of some other methods can be changed?

**Comment by mfursov** [comment]
Once you commit the change I will push v1.0.2 to maven

**Comment by solomax** [comment]
@mfursov, @tdunning, @martin-g  Could you please review my changes

**Comment by martin-g** [comment]
added few comments to the commit.

**Comment by solomax** [comment]
So, what will be the conclusion? should I revert my changes? Or it's OK to keep it?

**Comment by martin-g** [comment]
I'm OK to keep it.
