### ISSUE TITLE
Usage of JSONString

### ISSUE THREAD

**Issue by sebfz1** [openjson/openjson#8]
Hi,

This is a follow up question from [1] related to commit https://github.com/openjson/openjson/commit/d2367f28cebd8f21c4a4e22faec4cab2f8a95982. In sort: what should be the usage of `JSONString` interface?

The string is the textual representation of the json which serves serialization/deserialization purpose. So `#toJSONString` helps any bean to render this json string the way the user decides. On deserialization time, `JSONObject(String)` ctor takes that string in input, and the loop is looped.

Now: what about the `JSONObject(Object)` ctor, considering the supplied object also implements `JSONString`? 
1. Should `#toJSONString` only be used on `#toString` time? 
2. Or should `#toJSONString` also be evaluated and serves as input on ctor time?

[1] http://apache-wicket.1842946.n4.nabble.com/VOTE-Release-Apache-Wicket-7-7-0-tp4677714p4677737.html

**Comment by sebfz1** [comment]
Anybody?

**Comment by mfursov** [comment]
Could you check v1.0.4 please?

**Comment by solomax** [comment]
@mfursov 1.0.4 contains my implementation, it differs from org.json behavior
 this is why this discussion has been started

**Comment by mfursov** [comment]
Ok, I see now. 
@solomax  Is there any reason why we need to handle toJSONString in constructor and be incompatible both with org.json and Android API ?

**Comment by solomax** [comment]
This is what I'm confused about :(
It seems I have misread the original issue reported ...
I thought toJSONString should be called while constructing objects, since it provides "canonical" JSON representation of the object ....

I can change my commit to call `toJSONString` from `toString`, and not to use `toJSONString` in constructor
Would it be OK?

**Comment by mfursov** [comment]
@solomax I believe this will be the currect solution. Once you commit I can release new version to Maven

**Comment by solomax** [comment]
@mfursov I just realized I don't know how this can be implemented :(
`bean` is only available during construction, `toString` can be called anytime ....
Would appreciate help here

**Comment by mfursov** [comment]
Could you check this commit please:
https://github.com/openjson/openjson/commit/41f4573f6d0979c71ac52fda6d0d1307f647890f

**Comment by solomax** [comment]
Just have double-checked the code
It will work with `put` without any changes
The issue only reproducible in case bean is used in the constructor :(
This fix doesn't address it :(

**Comment by mfursov** [comment]
@solomax could you post a test case that will demonstrate the issue, please?

**Comment by solomax** [comment]
sure:

```
MyPojo2 myPojo2 = new MyPojo2();
String json2 = new JSONObject(myPojo2).toString();
assertEquals("{\"myProp3\":\"value3\",\"myProp4\":\"value4\",\"myProp5\":\"value5\"}", json2);
```

`toJSONString` will never be called ....

**Comment by mfursov** [comment]
Why this is an issue? Org.json also does not call toJSONString for Object constructor.

**Comment by solomax** [comment]
Actually this was the original issue: http://apache-wicket.1842946.n4.nabble.com/VOTE-Release-Apache-Wicket-7-7-0-tp4677714p4677735.html

This is what I originally try to fix

**Comment by mfursov** [comment]
AFAU the issue reported in that thread is not a regression but rather suggestion of a new feature that makes us incompatible with org.json.

I would suggest to roll the code back like I did in the issue-8 branch. I agree that calling toJSONString could be a good behaviour, but any new incompatibility with org.json is something we should avoid at least in v1 branch.

**Comment by solomax** [comment]
OK with me
@sebfz1 WDYT?

**Comment by sebfz1** [comment]
This is actually a regression. Please give me a couple of days to make a
simple project with testcases for both libraries...

**Comment by solomax** [comment]
Sure :)

WBR, Maxim
(from mobile, sorry for the typos)

**Comment by sebfz1** [comment]
Hi, sorry for the delay!

You can find here some tests upon org.json (latest), wicket (7.x) and opensjon (1.0.5).
https://github.com/sebfz1/openjson-issues/tree/master/src/test/java/com/example

There is something really strange :  `new JSONObject(myPojo).toString()` just does not call `#toJSONString` in any of these cases. Either my test is bad or I didn't understood the javadoc correctly...

> The JSONString interface allows a toJSONString() method so that a class can change the behavior of JSONObject.toString(), JSONArray.toString(), and JSONWriter.value(Object). The toJSONString method will be used instead of the default behavior of using the Object's toString() method and quoting the result.

But - fasten your seatbelt - if beans are in a List, then is works as expected, meaning: `new JSONArray(myArray).toString()` calls `#toJSONString`. This is valid for wicket & org.json but fails with openjson.

The actual test results are:
```
OrgJsonTest.testBeanJSONString:30 expected:<...","myProp4":"value4"[,"myProp5":"value5"]}> but was:<...","myProp4":"value4"[]}>
WicketJsonTest.testBeanJSONString:30 expected:<...","myProp4":"value4"[,"myProp5":"value5"]}> but was:<...","myProp4":"value4"[]}>
OpenJsonTest.testBeanJSONString:31 expected:<...","myProp4":"value4"[,"myProp5":"value5"]}> but was:<...","myProp4":"value4"[]}>

OpenJsonTest.testArrayJSONString:42 expected:<...","myProp4":"value4"[,"myProp5":"value5"]}]> but was:<...","myProp4":"value4"[]}]>
```

**Comment by mfursov** [comment]
The reason of the issue is OpenJSON's JSONObject.wrap does wrap JSONString objects as beans, but org.json's ones does not. 

Here is a patch (in a separate branch) to unify behavior of OpenJSON with org.json:
https://github.com/openjson/openjson/commit/427087efb1c9d9d737cfbe237caf1c1812664a5c

I can't say if I like this patch, but since the priority is to be compatible I believe we have to follow this way.

WDT?

**Comment by mfursov** [comment]
Looks like I have some white-spaces diffs in the patch. Please ignore them, they won't go to the mainline anyway.

**Comment by sebfz1** [comment]
I ran the tests over the `issue-8` branch and it works as expected!
Please let me know when the fix is going to be applied on master and the new released be issued, thank you very much! :)

**Comment by solomax** [comment]
Thanks for addressing this @mfursov :)

**Comment by klopfdreh** [comment]
Great to see the issue being addressed. Thanks!

Hopefully those are the last issues about json and the new version of Wicket can be released soon.

**Comment by mfursov** [comment]
Update was released to maven
