### ISSUE TITLE
Object with array property fails on NPE when construction JSON object

### ISSUE THREAD

**Issue by martin-g** [openjson/openjson#9]
From https://issues.apache.org/jira/browse/WICKET-6400:

If we have an Object (POJO) that includes array(s), it fails on java.lang.NullPointerException when I pass it as an argument to the JSONObject constructor.
The cause is that JSONArray cannot be included in the JSONObject anymore because of absence of some readMethods (it fails on NPE at line 234 in JSONObject). I assume this is caused by switching to open-json.
Simplest example:

```java
    public static void main(final String[] args) {
        final JSONArray array = new JSONArray(new Object[] { 1, 2, 3 });
        new JSONObject(array);
    }
```

fails on:

```
Exception in thread "main" java.lang.NullPointerException
        at org.apache.wicket.ajax.json.JSONObject.propertiesAsMap(JSONObject.java:234)
        at org.apache.wicket.ajax.json.JSONObject.<init>(JSONObject.java:225)
        at cz.kb.dcs.module_frontend_base.components.graph.renderer.GraphRendererJSONUtils.main(GraphRendererJSONUtils.java:53)
```

**Comment by solomax** [comment]
Hello @martin-g, what is expected JSON in this case?

**Comment by martin-g** [comment]
I guess whatever JSON2 lib produced.
I haven't tried it. Just forwarded the issue from Wicket JIRA.

**Comment by solomax** [comment]
@martin-g 
Just have tried following code:
```
        final org.json.JSONArray arr = new org.json.JSONArray(new Object[] { 1, 2, 3 });
        org.json.JSONObject obj = new org.json.JSONObject(arr);
```
The result is empty object `{}`, is it acceptable?

As an alternative the result might be: `{"0": 1, "1": 2, "2": 3}` i.e. index will be the key
WDYT?

**Comment by martin-g** [comment]
I think it should be an empty object. To be backward compatible.

**Comment by martin-g** [comment]
For some reason the commit message didn't close the issue.
I'll copy the fix to Wicket 6.x and 7.x.
For 8.x we will need a new version of OpenJson to be released.

**Comment by martin-g** [comment]
Thanks, @solomax !

**Comment by martin-g** [comment]
Actually, we don't really need the new release for Wicket 8.x.
The application can use latest openjson if it needs this fix.
I'm closing the ticket in Wicket JIRA.

**Comment by mfursov** [comment]
http://repo1.maven.org/maven2/com/github/openjson/openjson/1.0.7/

**Comment by martin-g** [comment]
Thank you, @mfursov !
